name: Vagrant Virtualbox box publish

on:
  push:
  schedule:
    - cron: "1 1 * * 1"

jobs:
  box_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup HashiCorp Packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest
      - name: Setup HashiCorp Vagrant
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update
          sudo apt install -y vagrant
      - name: Setup Virtualbox
        run: |
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list
          wget -O- https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo gpg --yes --output /usr/share/keyrings/oracle-virtualbox-2016.gpg --dearmor
          sudo apt-get update
          sudo apt-get install -y build-essential software-properties-common virtualbox
      - name: Check versions
        run: |
          vagrant --version
          packer --version
          vboxmanage --version
      - name: Build box artifact
        run: |
          export VIRTUALBOX=true
          make build
      - name: Upload build artifact
        env:
          VAGRANT_TOKEN: ${{ secrets.VAGRANT_TOKEN }}
        if: github.ref  == 'refs/heads/main'
        run: |
          export VERSION="$(date +%Y%m%d).${{github.run_number}}.${{github.run_attempt}}"
          echo "VERSION=$VERSION"
          make upload
